from __future__ import annotations

from enum import StrEnum


class StepStatus(StrEnum):
    PENDING = "PENDING"
    READY = "READY"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"
    BLOCKED = "BLOCKED"
    INVALIDATED = "INVALIDATED"
    REQUIRES_CONFIRMATION = "REQUIRES_CONFIRMATION"


class SideEffect(StrEnum):
    PURE = "PURE"
    WORKSPACE_WRITE = "WORKSPACE_WRITE"
    NETWORK_READ = "NETWORK_READ"
    EXTERNAL_WRITE = "EXTERNAL_WRITE"
    DESTRUCTIVE = "DESTRUCTIVE"


class RetryMode(StrEnum):
    NEVER = "NEVER"
    ONCE = "ONCE"
    BOUNDED = "BOUNDED"


class FailureKind(StrEnum):
    NON_ZERO_EXIT = "NON_ZERO_EXIT"
    TIMEOUT = "TIMEOUT"
    SIGNAL = "SIGNAL"
    OUTPUT_VIOLATION = "OUTPUT_VIOLATION"
    PROCESS_INTERRUPTED = "PROCESS_INTERRUPTED"
    INTERNAL = "INTERNAL"


class Decision(StrEnum):
    REUSE = "REUSE"
    RETRY = "RETRY"
    RERUN = "RERUN"
    BLOCK = "BLOCK"
    CONFIRM = "CONFIRM"
    SKIP = "SKIP"


class ReasonCode(StrEnum):
    SUCCESS_CONTRACT_MATCH = "SUCCESS_CONTRACT_MATCH"
    INPUT_CHANGED = "INPUT_CHANGED"
    OUTPUT_MISSING = "OUTPUT_MISSING"
    OUTPUT_CHANGED = "OUTPUT_CHANGED"
    RUNBOOK_CHANGED = "RUNBOOK_CHANGED"
    COMMAND_CHANGED = "COMMAND_CHANGED"
    POLICY_CHANGED = "POLICY_CHANGED"
    DEPENDENCY_INVALIDATED = "DEPENDENCY_INVALIDATED"
    DEPENDENCY_FAILED = "DEPENDENCY_FAILED"
    FAILURE_RETRYABLE = "FAILURE_RETRYABLE"
    FAILURE_NOT_RETRYABLE = "FAILURE_NOT_RETRYABLE"
    SIDE_EFFECT_CONFIRMATION = "SIDE_EFFECT_CONFIRMATION"
    STALE_RUNNING_ATTEMPT = "STALE_RUNNING_ATTEMPT"
    PLAN_STALE = "PLAN_STALE"


class EvidenceMode(StrEnum):
    STANDARD = "STANDARD"
    REDACTED = "REDACTED"
